### ISSUE TITLE
Cache npm tools

### ISSUE THREAD

**Issue by stefanoruth** [NiclasHedam/ubuntu-laravel#1]
Hvad nu hvis vi i billeder laver en global install af fx webpack og nogle af de andre js libaries så de ligger i serverens cache frem for at skulle hentes fra ny hver gang?

**Comment by stefanoruth** [comment]
Evt. gøre det samme med composer

**Comment by NiclasHedam** [comment]
Det er sådan set ikke helt dumt.
Jeg har det lige i baghovedet
