### ISSUE TITLE
HTTP2

### ISSUE THREAD

**Issue by stefanoruth** [NiclasHedam/ubuntu-laravel#2]
Kunne måske være intrassant at slå h2 til på apache serveren.

**Comment by NiclasHedam** [comment]
Det tror jeg ikke er supported i den version af apache der kommer med 16.04

**Comment by stefanoruth** [comment]
Hva version af apache er der på 16.04 da? Modulet require 2.4.17+ https://httpd.apache.org/docs/2.4/mod/mod_http2.html

**Comment by NiclasHedam** [comment]
https://wiki.ubuntu.com/XenialXerus/ReleaseNotes#HTTP.2F2_support_in_Apache_httpd

**Comment by stefanoruth** [comment]
Ja det er fra omkring april 2016, der var sørme heller ikke support for hverken php7 eller php7.1 på den ubuntu release

**Comment by NiclasHedam** [comment]
Må evt. se på om vi kan få 17.04 på.
